### ISSUE TITLE
FATAL ERROR - ADD FRONT-END ITEM

### ISSUE THREAD

**Issue by moXion** [getk2/k2#130]
I've just notice this situation today, due a report from a collaborator that have access to add items in front end. 
When trying 'Add Item' , the popup window give error: 

Fatal error: Call to a member function isCheckedOut() on a non-object in /hsphere/local/home/c290983/theazores.pt/administrator/components/com_k2/views/item/view.html.php on line 100! 

Everything works fine in the administration, I can add/edit items with no problem. 

System: 
- Joomla 3.2.3 
- K2 2.6.9 (Develper Build) - The problem starts with 2.6.8 version, I've just install de Developer Version to see if this fix this problem. 

Appreciate your help, this is URGENT. 

Regards and thank you, 

Pedro

**Comment by andergmartins** [comment]
I was able to reproduce this issue on a client site today. 

After debugging I found out that when you call the task item.add, it will load the view K2ViewItem from the admin. That is ok, but inside the view it is loading the wrong model class. 

You can check that on this line:
https://github.com/andergmartins/k2/blob/master/administrator/components/com_k2/views/item/view.html.php#L44 we get the instance of the module, specifying the class prefix: K2Model. That is correct. But on the line https://github.com/andergmartins/k2/blob/master/administrator/components/com_k2/views/item/view.html.php#L43 we don't add the path to the correct prefix, since there is no prefix.
According to my tests, if you omit the prefix, the line 44 will result in an instance of the frontend module (which path is already there, since we are on the frontend) instead of the model from the backend. It is clear that we are expecting a model from the backend because we are calling methods like isCheckedOut which is only available on the class provide by the backend.
