### ISSUE TITLE
Feature request: Article - MultiCategories Support

### ISSUE THREAD

**Issue by Xcantion** [getk2/k2#183]
Feature request: Article - MultiCategories Support for K2

**Comment by Robdebert** [comment]
It does work, you only need to fix the php file.

See: https://github.com/yakuzmenko/bereg/issues/4

**Comment by Robdebert** [comment]
I just added a bugfixed version here: https://github.com/Robdebert/k2additionalcategories
You can simply download it as zip and install in joomla.

Please test if it works and report any bugs via my repository.

I hope it is ok to do so, because the author of the original plugin does not seem to respond.
