### ISSUE TITLE
Is it possible to add Google reCAPTCHA

### ISSUE THREAD

**Issue by Simon-Davies** [getk2/k2#251]
Is it possible to add Google reCAPTCHA for comments into the developer build? The new Google reCAPTCHA looks so much better.

**Comment by kavadas** [comment]
Hi,

K2 already includes the Google reCAPTCHA. However, in order to integrate the new version we need to make some changes to the layouts which will cause backwards compatibility issues for sites that make use of layout overrides. We need to find a solution that will not break reCAPTCHA on existing sites. Any suggestions/ideas are welcome.

**Comment by fevangelou** [comment]
Perhaps a new set of template overrides. We were discussing with Krikor the option for a new modern layout for K2. Perhaps we could use that there and add a switch in the backend to enable either v1 or v2 of reCaptcha.

**Comment by Simon-Davies** [comment]
Having a switch to enable v1 or v2 sounds like a really good idea :)
