### ISSUE TITLE
creating a menu for all tags in k2

### ISSUE THREAD

**Issue by solan007** [getk2/k2#304]
hi

i want to create a menu for my all tags not selected tag in k2

as you know we can do that via joomla content component but in k2 we have to select one tag

i think it is a good idea to improving of seo.

**Comment by fevangelou** [comment]
Joomla does a lot of stupid things. We should only keep the good parts you know. Making a menu item pointing to ALL your tags is bad from a performance standpoint. Very bad. Since all your content belongs to some category, why not just retrieve content from ALL your categories, which, if you think about it, is what you already want.

**Comment by solan007** [comment]
if you try easyblog, jsitemap extensions you will see that these extensions have a menu for all tags

a page for tag with paging and limitation of tags and rss of tags
