### ISSUE TITLE
unwanted behaviour in creating menuItem new K2 Article

### ISSUE THREAD

**Issue by mazarata** [getk2/k2#308]
Hi there,
I am creating a new menuItem to allow my users to create content with K2. I am following standardprocedure in Joomla Admin Backend. After I chose K2 menu component, in the details tab, I want to use the target window to be the same, but it switches all the time to option new target window without navigation. Please refer to this movie: http://www.2globetrotter.ch/dev/k2_MenuItemCreation.mp4.

Also very unusual is the url produced, when I want to open the item through the Menu. It tries to open /index**2**.php/de/..... instead of classically /index.php/de/...

Any idea, where this may come from? Thanks for your help.
Regards, Giuseppe
[k2_file.pdf](https://github.com/getk2/k2/files/212802/k2_file.pdf)

**Comment by pepperstreet** [comment]
Wow, as time flies by… ;) 

Old topic, but currently I have noticed the same issue with MenuItem type "K2 Item edit form".  
On Save, the menuitem parameter "Target Window" reverts to "New Window with Navigation"?! 

Probably this parameter should not be considered at all… 
since all other K2 edit links open in a **modal** and get an additional "&tmpl=component" in their URL. 

I believe, this is a **bug**.
