### ISSUE TITLE
Implement Google's new Invisible reCAPTCHA 

### ISSUE THREAD

**Issue by Simon-Davies** [getk2/k2#405]
It would be nice if you guys could Implement Google's new Invisible reCAPTCHA for comments.

**Comment by fevangelou** [comment]
Thanks

It's in my to-do list already. I'll keep it along with reCAPTCHA v2 and add a switch to select which one you want used. Since my plan is to roll out K2 v2.8.0 the coming days (hopefully this Friday), I'll push this update to 2.9.0 to be released in September. In general the plan is to roll out releases more often (but not every week or two obviously)...

**Comment by shoulders** [comment]
could you use the joomla system recaptcha plugin for this

**Comment by fevangelou** [comment]
Seeing how the J API constantly changes, we're moving (architecturally wise) to separating our code as much as possible from internal dependencies in Joomla. That being said, we'll continue using a separate implementation.

**Comment by Simon-Davies** [comment]
Is this still being added? It's a year later but still no invisible ReCAPTCHA :(

**Comment by fevangelou** [comment]
It's one of the last things to implement before releasing v2.9.0 in the coming days (well, that and removing Google Search integration which is deprecated now).

**Comment by fevangelou** [comment]
Do you mean the character count in the search field? This was actually removed a while back because we were cutting off legit searches :) But I can surely add a custom limit to enforce if needed.

As for donating and supporting K2, you have the following options:
- Either purchase a subscription to one of our commercial extensions from joomlaworks.net
- Become a patron at https://www.patreon.com/getk2
- Direct donation via PayPal: https://www.joomlaworks.net/donate-to-k2 (redirects to PayPal link)

**Comment by Simon-Davies** [comment]
I mean the character count when it shows k2 items that fit the search word. It will display all the item that fit it. 

Is there a way of limiting it to only shows so many characters in each item it displays in the search.

**Comment by Simon-Davies** [comment]
So don't display every full item that fits it but only so many characters from each item so you are not scrolling and scrolling.
