### ISSUE TITLE
Enhancement: Render editor plugins in extrafields

### ISSUE THREAD

**Issue by kricore** [getk2/k2#415]
Sauce here: http://www.joomlaworks.net/forum/k2-en/47315-extra-fields-missing-options-in-the-toolbar-of-the-editor

**Comment by fevangelou** [comment]
TinyMCE based editors were loaded by default, otherwise there was a fallback to NicEdit. I've updated how we load Joomla's TinyMCE (so it loads all options as selected in that plugin, which resolves the issues mentioned in that forum post you linked to) and fixed the height issue that occurred with JCE (which resulted in an extremely short editor window).
