### ISSUE TITLE
Feature Request: category image upload to multiple sizes

### ISSUE THREAD

**Issue by williamconifer** [getk2/k2#440]
I would love to have the category image work in the same manner as the k2 item image. When you upload a category image it would get resized into xs to xl versions. This would allow me to use srcset for a category landing page. 

Thank you.

**Comment by kbrookes** [comment]
I'd love this as well.

**Comment by fevangelou** [comment]
I can already imagine the negative comments for that. Honestly though, I think it's overkill. Category images are rarely used for presentation. It's waaaaaay better to just move forward and allow extra fields to load in the category (like we do with items). Since the new architecture for extra fields that I'm preparing is modular/extensible, it will be a lot easier creating your own version that does exactly what you say. Think of the upcoming extra fields as a Joomla/K2 plugin but without the packaging hassle and only 3 files as bare minimum (setup, input, output).

**Comment by ronnyvanderborght** [comment]
As much as I have always loved k2's extra fields, it would be nice to have an extra fields like the SQL Query field from Joomla's custom fields. You can do very powerfull stuff with this. My absolute dream: a repeatable field. From a developer point of view k2's extra fields are super easy to use and very powerfull, but from a UI point of view I must say the Joomla's custom fields are not bad at all. Is it a thought to make k2's extra fields compatible with Joomla's ?
