### ISSUE TITLE
update.js in joomla admin - is this needed any more

### ISSUE THREAD

**Issue by shoulders** [getk2/k2#444]
when I load K2 in the admin the following asset is loaded
`https://getk2.org/app/update.js?t=20180316`

Is this neeed anymore with having a Joomla update system?

Also this is an external asset and reduces load time.

**Comment by fevangelou** [comment]
It's nice to have. I'll add a switch to disable it, but so far the feedback we've got is that it reminds users to update in a better way. Which is why we'll open the notification to managers as well, so authors push the site admin to upgrade sooner. I'll combine these options to a single switch in the admin.

**Comment by fevangelou** [comment]
For reference, it was originally added as a way to have a unified update notification on Joomla versions 1.5 to 3.x.
