### ISSUE TITLE
Feature Request: Add option to load static files locally

### ISSUE THREAD

**Issue by kricore** [getk2/k2#447]
Cloudflare seems to be behaving strangely in certain areas.
Sauce here: https://www.joomlaworks.net/forum/k2-en/48974-why-does-k2-have-to-load-cloudflare-s-cdn-files#166810

**Comment by ycway** [comment]
I really need this feature because the loading of these CDN files will affect my site management and browsing.

Thanks.

**Comment by afonic** [comment]
This would be a good feature, because loading from a CDN also affects developing when offline. I know it's not very frequent but I often develop sites without a reliable internet connection and if I clear the browser's cache the backend does not work.

So an option to load the files locally would help issues like these.

**Comment by errotu** [comment]
is there any development regarding this? Also keeping in mind the GDPR it would make sense to have an option to load static files locally.

Thanks for all your great work!
