### ISSUE TITLE
New function getTotal doesn't work when falang is installed

### ISSUE THREAD

**Issue by jameswadsworth** [getk2/k2#515]
In version 2.10.x the new getTotal method of using SQL_CALC_FOUND_ROWS and then SELECT FOUND_ROWS() does not work in the front end when falang is installed for translation.  When falang is installed  and actived getTotal returns always 0 and so the pagination no longer works. 

Steps to reproduce. 
1) create some items in K2 and add to a category
2) view the category in the front end and notice the pagination works correctly
3) install falang and see the pagination is no longer there
4) disable falang and the pagination returns.

**Comment by fevangelou** [comment]
It's been addressed in K2 v2.10.3 (dev) which you can grab from: https://getk2.org/downloads/?f=K2_Development_Release.zip

**Comment by jameswadsworth** [comment]
Hi Fotis, we have installed the developer release and we can confirm this resolves the issue. Cheers.

**Comment by sebdavid** [comment]
Hi, 
I think I'm concerned by this issue to, because we have K2 2.10.2 + Falang installed, and no more pagination displayed. The config looks good, and the pagination object contains the following (pagesTotal & total set to 0) :
```json
{"limitstart":0,"limit":10,"total":0,"prefix":"","pagesStart":1,"pagesStop":0,"pagesCurrent":1,"pagesTotal":0, ...}  
```
I don't know what is the current state of the dev version of 2.10.3, but it seems that the official release is in the pipe (https://www.joomlaworks.net/forum/k2-en/51718-limit-of-items-in-category-view?start=10#175427). So I'm gonna wait for it impatiently !

**Comment by fevangelou** [comment]
You can safely use it now and just upgrade again when it's out in the
coming days.
