### ISSUE TITLE
When is K2 for joomla 4?

### ISSUE THREAD

**Issue by ARTIS-MEDIA** [getk2/k2#554]
Hello. When is K2 for joomla4? Only this component is blocking me and my other clients from migrating the website to joomla 4.

**Comment by cmirnow** [comment]
Similar question....

**Comment by jameswadsworth** [comment]
Same here.....

**Comment by fooo0z0oool** [comment]
I wait too...

**Comment by ARTIS-MEDIA** [comment]
Time to give up K2. There is some misunderstanding with such support.

**Comment by felipeabranches** [comment]
Me too

**Comment by uAGRwz** [comment]
Same. I wait new version of K2. For Joomla 4

Завантажте Outlook для iOS<https://aka.ms/o0ukef>
________________________________
Від: Felipe Abranches ***@***.***>
Надіслано: Sunday, August 28, 2022 1:05:27 PM
Кому: getk2/k2 ***@***.***>
Копія: Subscribed ***@***.***>
Тема: Re: [getk2/k2] When is K2 for joomla 4? (Issue #554)


Me too

**Comment by mgscreativa** [comment]
The same here, any update on k2 J4 dev?

**Comment by rinka88** [comment]
> Как перенести статьи из K2 в основную систему?

https://www.joomlart.com/documentation/joomla-plugins/k2-to-com-content-migration-plugin

**Comment by ARTIS-MEDIA** [comment]
Thanks for the link. As you can see, most people are planning to go back to joomla. It's a pity the guest is wasting such a good component.

**Comment by raramuridesign** [comment]
@fevangelou Any feedback on a J4 version of K2... ie a date or an idea on a release...

**Comment by fevangelou** [comment]
Once custom projects we're working on are done around Jan 2023 :)

**Comment by ARTIS-MEDIA** [comment]
Hello, do you already know when you will release K2 for joomla4? do you know the date?

**Comment by anibalsanchez** [comment]
For the record: [K2 v2.11, rolling releases, Joomla 4 and more](https://getk2.org/blog/k2-v2-11-rolling-releases-joomla-4-and-more)

**Comment by ARTIS-MEDIA** [comment]
I've read it and it doesn't make any sense. Probably another year will have to wait until joomla 5 appears.

**Comment by anibalsanchez** [comment]
Theoretically, J5 will be iterative, and they won't deprecate APIs. 

Of course, we never know until the time comes if J5 will be delayed for more years, if J5 will come with plenty of BCs, or if J3 won't be supported for more time. So, plans have to weigh in all scenarios.

**Comment by fevangelou** [comment]
@ARTIS-MEDIA H1 2023 - We got a major media/news project for June 2023 and it's gonna be built in J4.

@anibalsanchez The PHP side is not the biggest deal here. It's mostly the UI which needs to be adapted for J4 (let's not forget the moving sidebar too). We're gonna go with as much specificity possible under our own CSS namespace to avoid potential issues & styling collisions in the future. And also make it easier to upgrade to J5, J6 or whatever comes.

@all
We're invested in Joomla for 2 reasons:

a) we like the platform since it was called Mambo & we are fluent with it to tailor as we like and
b) we focus 100% on projects for media sites (=K2) and as such, we don't really care whether widespread support is available for Joomla. E.g. if other major extensions drop support for Joomla, we're not affected and certainly won't be influenced to drop support for Joomla as well.

As long as Joomla keeps the lights on, we'll support it with K2 and our other extensions. Cause we see Joomla as a platform (much like an OS).

At some point K2 will also support WordPress (out of client demand mainly, not personal preference). Cause the closest one can get to K2 in WordPress is a bunch of ACF form fields and lots of duct tape. It's not an elegant solution but it's the best for WP right now. I believe we can do better as we did with K2 already for Joomla.

And for anyone thinking K2 is "not really needed because Joomla has tags and whatnot" think again... K2's power is not its direct features, but its ease of configuration, its performance and by far its templating.

**Comment by raramuridesign** [comment]
@fevangelou looking forward to the regular updates on code ;-)

**Comment by ARTIS-MEDIA** [comment]
Too long for me to wait. I have already migrated one site to the core system. Lots of work but we made it. Thanks for K2. It's a pity to part with K2. I have to wait too long for updates. Regards.

**Comment by rinka88** [comment]
> Too long for me to wait. I have already migrated one site to the core system. Lots of work but we made it. Thanks for K2. It's a pity to part with K2. I have to wait too long for updates. Regards.

https://joomhelper.com/k2-to-content
maybe it will help you
