### ISSUE TITLE
com_k2_extended cache 17 GB and non stopping growing!!!

### ISSUE THREAD

**Issue by itmagpro** [getk2/k2#563]
Hello bro,

```
Joomla 3.x
+
K2 v2.11.20230505
Copyright © 2006-2024 JoomlaWorks Ltd.

(OR K2 v2.11.xx NOT SUPPORT Joomla 3.x ???)
```

We have **HUGE PROBLEM WITH YOUR com_k2_extended CACHE**:

1. com_k2_extended cache abnormal growing in /cache/com_k2_extended dir and non stop any way!!!
2. WE NOT HAVE SO MANY POST'S FOR THIS CRAZY com_k2_extended CACHE SIZE !!! 
3. /cache/com_k2_extended cache NON STOP GROWING, AND HAVE MANY MANY DUPES - fdupes APPROVE THIS!!!

Sample dupes cache files with different names, that finds fdupes program:

```
/cache/com_k2_extended/5bcecfbf0285810c7684ebdf955539df-cache-com_k2_extended-3e3146b672520a10758baef6cda55b28.php
/cache/com_k2_extended/5bcecfbf0285810c7684ebdf955539df-cache-com_k2_extended-d12adf6e775c08590146ed96db42e6f9.php
/cache/com_k2_extended/5bcecfbf0285810c7684ebdf955539df-cache-com_k2_extended-3c708a0a6ee9121d4eba437bca93cd37.php
```

CACHE NOT AUTO UPDATED!!! CACHE NOT AUTO REMOVED!!! **CACHE JUST ABNORMAL GROWING!!! NEW DUPES CACHE FILES WITH DIFFERENT NAMES CREATED AGAIN, AGAIN AND AGAIN...**

**None any installed plugins or components with this com_k2_extended name, also none any knob or any settings for manage this crazy com_k2_extended cache ;(**

/cache/com_k2_extended CRAZY CACHE this is part of com_k2 component??? **Where shit code, that produce /cache/com_k2_extended CRAZY CACHE ???**

**HOW WE CAN DISABLE/STOP/REMOVE/FIX THIS CRAZY BEHAVIOR com_k2_extended CACHE ???** OR REMOVE com_k2_extended without remove com_k2 component!?

com_k2_extended cache problem described here:
[https://itmag.pro/server/common/com-k2-extended-cache](https://itmag.pro/server/common/com-k2-extended-cache)

_P.S. FROM WHERE GROW HANDS IN com_k2_extended DEVELOPERS WHO CREATE THIS CRAZY com_k2_extended CACHE SYSTEM !!!???_

**Comment by fevangelou** [comment]
The extended cache does extra caching on top of Joomla's. It serves a purpose, it wasn't done "just because".

Your issue stems from 2 facts:
a) Your cache probably never expires. It should.
b) You are using disk storage instead of APCu, Memcached or Redis. Try changing to one of these and you'll get a speed boost as well.

I would also recommend some proper setup for cache-control headers. Either utilize the Page Cache system plugin or use ours (better): https://github.com/joomlaworks/url-normalizer

Some tuning on the server software wouldn't hurt as well.

K2 powers not some but THE highest traffic sites ever built with Joomla for a reason.

**Comment by fevangelou** [comment]
Whatever.
