### ISSUE TITLE
Enhancement: Extra fields and Params in Separate Tables and Fields

### ISSUE THREAD

**Issue by murphylas** [getk2/k2#87]
We recently had to move a web site from another system to K2. We used SQL to populate the k2 items (almost 4,000 items). Everything worked well except extra_fields and params  which required very complex and difficult SQL statements to parse and produce the strings necessary to fill and modify extra fields and params.

Please use linked tables with separate fields to handle these items. 

This also helps when performing queries on the tables.

**Comment by djacouma** [comment]
This is a couple years too late to help, but since I just went though a similar process, I figured that I might as well post my approach for others to pick from and use.  it's Klonky, but worked like a charm.

So… if you had:

• Non joomla table with source data in same db as joomla tables: MySourceTable
• MySourceTable has columns SourceDataFieldName_1 to 8 and SourceDataFieldNumber_1 and 2
• Joomla db table prefix: JPFX_

1. Create extra field group
2. Create extra fields and assign to extra field group
3. Assign extra field group to k2 category
4. Manually create a k2 item and fill extra fields in with sample data from a record that you are going to import, and set it to published.  Close it, open it again, and “save and close”
5. Go to PHPMyAdmin
6. Copy the contents of JPFX_k2_items.extra_fields to a plain text file on your desktop for reference
7. Copy the contents of JPFX_k2_items.extra_fields_search to another plain text file on your desktop for reference
8 Export your JPFX_k2_items MYSQL tabqle to a CSV file
9. Open the CSV file in Excel
10. Clone that first record to make 4000 rows of idential column data
11. Generate column A “id” values from 1 to 4000 (assuming that you have no real k2 articles in the system other than the sample).
12. Load your source data table ‘MySourceTable’ into excel as well
13. Select and copy the alias or equivalent UNIQUE column (let’s call it `UniqueSourceID`) of 4000 values from ‘MySourceTable’, and paste it into the ‘alias’ column of the JPFX_k2_items table (still in excel)
14. Delete all data from title, extra_fields, extra_fields_seach, introtext, fulltext etc from all 4000 records
15. Save as CSV and re-import as CSV into PHPMyAdmin, and overwrite original table
16. Paste this (modified with your source field names) in the SQL window of PHPMyadmin and click “GO”.

UPDATE `JPFX_k2_items` set `extra_fields`= (SELECT
	CONCAT("[",
   		GROUP_CONCAT(
            CONCAT ("{\"id\":\"1\",\"value\":\"",`SourceDataFieldName_1`,”\”},”),
            CONCAT ("{\"id\":\"2\",\"value\":\"",`SourceDataFieldName_2`,"\"},"),
            CONCAT ("{\"id\":\"3\",\"value\":\"",`SourceDataFieldName_3`,"\"},"),
            CONCAT ("{\"id\":\"4\",\"value\":\"",`SourceDataFieldName_4`,"\"},"),
            CONCAT ("{\"id\":\"5\",\"value\":\"",`SourceDataFieldName_5`,"\"},"),
            CONCAT ("{\"id\":\"6\",\"value\":\"",`SourceDataFieldName_6`,"\"},"),
            CONCAT ("{\"id\":\"7\",\"value\":\"",`SourceDataFieldName_7`,"\"},"),
            CONCAT ("{\"id\":\"8\",\"value\":\"",`SourceDataFieldName_8`,"\"},"),
            CONCAT ("{\"id\":\"18\",\"value\":",`SourceDataFieldNumber_1`,"},"),
            CONCAT ("{\"id\":\"19\",\"value\":",`SourceDataFieldNumber_2`,"}")        
        )
	,"]")
as json FROM `MySourceTable ` WHERE `JPFX_k2_items`.`alias` = `MySourceTable `.`UniqueSourceID `)

17. Copy a sample from one of the extra_fields cell records, and check it at http://jsonlint.com/ to make sure you got it the JSON format right.

18. Update other columns one by one as needed with SQL like this

UPDATE `JPFX_k2_items ` set `DestField`= (
	SELECT `SourceField` FROM `MySourceTable ` WHERE `JPFX_k2_items`.`alias ` = `MySourceTable `.`UniqueSourceID `)

19. Note that you need to also generate the Extra_fields_search column data, which is in essence idential to the json one, but without any kind of seperators or punctuation.  Alternatively, you could set an intern up to manually open and “Save and Close” each article in the back end, which will complete that field for you and possibly clean up more or add in another other code for other plugins that you have installed.

**Comment by kavadas** [comment]
@djacouma 

Thank you for sharing this. However, since this is a place for submitting issues, you might want to also share this with the K2 community at our forum at http://www.joomlaworks.net/forum/ .

**Comment by djacouma** [comment]
My pleasure… although I’m sure that there are 100 gurus on the k2 forums who have way cleaner methods to propose!
